# code: language=ansible
---
- name: Download bash package
  become: true
  become_user: "{{ automated_user }}"
  ansible.builtin.get_url:
    url: "{{ bash_url }}"
    dest: "{{ sources_image.mount_point }}/{{ bash_url | basename }}"
    mode: "0644"

- name: Extract bash package
  become: true
  become_user: "{{ automated_user }}"
  ansible.builtin.unarchive:
    src: "{{ sources_image.mount_point }}/{{ bash_url | basename }}"
    dest: "{{ sources_image.mount_point }}"
    remote_src: true
    creates: "{{ sources_image.mount_point }}/{{ bash_version }}"

- name: Configure bash package
  become: true
  become_user: "{{ automated_user }}"
  ansible.builtin.command: |
    ./configure --prefix=/usr   \
    --host="{{ arch.stdout }}-automated-linux-gnu" \
    --build="{{ arch.stdout }}-automated-linux-gnu" \
    --without-bash-malloc              \
    --enable-static-link \
    bash_cv_strtold_broken=no
  register: result
  args:
    chdir: "{{ sources_image.mount_point }}/{{ bash_version }}"
  failed_when:
    - result.rc != 0
  changed_when: result.rc == 0

- name: Build bash package
  become: true
  become_user: "{{ automated_user }}"
  ansible.builtin.command: |
    make -j{{ nproc.stdout | int * 2 }}
  args:
    chdir: "{{ sources_image.mount_point }}/{{ bash_version }}"
  failed_when:
    - result.rc != 0
  changed_when: result.rc == 0

- name: Add include <unistd.h> after include "config.h" in bash
  become: true
  become_user: "{{ automated_user }}"
  ansible.builtin.lineinfile:
    path: "{{ sources_image.mount_point }}/{{ bash_version }}/lib/termcap/tparam.c"
    insertafter: "#include <config.h>"
    line: "#include <unistd.h>"

- name: Install bash package
  become: true
  become_user: "{{ automated_user }}"
  ansible.builtin.command: |
    make DESTDIR={{ root_image.mount_point }} install
  args:
    chdir: "{{ sources_image.mount_point }}/{{ bash_version }}"
  failed_when:
    - result.rc != 0
  changed_when: result.rc == 0

- name: Create sh link links
  become: true
  become_user: "{{ automated_user }}"
  ansible.builtin.file:
    src: "bash"
    dest: "{{ root_image.mount_point }}/bin/sh"
    state: link

- name: Remove bash directory
  become: true
  become_user: "{{ automated_user }}"
  ansible.builtin.file:
    state: absent
    path: "{{ sources_image.mount_point }}/{{ bash_version }}"
