# code: language=ansible
---
- name: Create toolchain
  hosts: "{{ host | default('localhost') }}"
  gather_facts: false
  become: true
  vars_files:
    - ../vars/automated-linux.yaml
  tasks:
    - name: Get TARGET environment variable
      changed_when: false
      ansible.builtin.command: |
        uname -m
      register: arch

    - name: Get TARGET environment variable
      changed_when: false
      ansible.builtin.command: |
        nproc
      register: nproc

    - name: Import binutils tasks
      ansible.builtin.import_tasks: toolchain/binutils.yaml
      vars:
        binutils_version: binutils-2.43.1

    - name: Import gcc stage1 tasks
      ansible.builtin.import_tasks: toolchain/gcc_stage1.yaml
      vars:
        gcc_version: gcc-14.2.0
        mpfr_version: mpfr-4.2.1
        gmp_version: gmp-6.3.0
        mpc_version: mpc-1.3.1

    - name: Import Linux Headers tasks
      ansible.builtin.import_tasks: toolchain/linux_headers.yaml
      vars:
        linux_version: linux-6.12.8
        url: https://www.kernel.org/pub/linux/kernel/v6.x/linux-6.12.8.tar.xz
