---
- name: Create toolchain
  hosts: "{{ host | default('localhost') }}"
  gather_facts: false
  become: true
  vars_files:
    - ../vars/automated-linux.yaml
  tasks:
    - name: Get TARGET environment variable
      changed_when: false
      ansible.builtin.command: |
        uname -m
      register: arch

    - name: Get TARGET environment variable
      changed_when: false
      ansible.builtin.command: |
        nproc
      register: nproc

    - name: Import binutils tasks
      ansible.builtin.import_tasks: toolchain/binutils.yaml
      vars:
        binutils_version: binutils-2.43.1
