---
- name: Automated-Linux Playbook
  hosts: "{{ host | default('localhost') }}"
  gather_facts: false

  vars:
    download_dir: "downloads"
    sources_dir: "sources"

  tasks:
    - name: Install bzip2 package
      become: true
      ansible.builtin.package:
        name:
          - bzip2
          - tar
          - gzip
          - xz-utils
        state: present
    - name: Create support directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      with_items:
        - "{{ download_dir }}"
        - "{{ sources_dir }}"

    - name: Download packages
      ansible.builtin.get_url:
        url: "{{ item }}"
        dest: "{{ download_dir }}/{{ item | basename }}"
        mode: "0644"
      with_items: "{{ download_result.results }}"
      loop: "{{ lookup('file', filepath) | split('\n') }}"
      vars:
        filepath: "../packages.txt"

    - name: List contents of download_dir
      ansible.builtin.find:
        path: "{{ download_dir }}"
        patterns: "*.tar.gz,*.tar.xz,*.tar.bz2"

      register: download_dir_contents

    - name: Extract packages
      ansible.builtin.unarchive:
        src: "{{ item }}"
        dest: "{{ sources_dir }}"
        remote_src: true
      with_items: "{{ download_dir_contents.files | map(attribute='path') }}"
