---
- name: Automated-Linux Prepare
  hosts: "{{ host | default('localhost') }}"
  gather_facts: false
  collections:
    - ansible.posix.mount

  vars:
    packages:
      - coreutils
      - bash
      - binutils
      - bison
      - diffutils
      - findutils
      - gawk
      - gcc
      - g++
      - grep
      - gzip
      - m4
      - make
      - patch
      - perl
      - sed
      - tar
      - texinfo
      - xz-utils
      - bzip2
    root_image:
      image: "automated-linux-root.img"
      size: "10G"
      mount_point: "/mnt/automated-linux"
    sources_image:
      image: "automated-linux-sources.img"
      size: "20G"
      mount_point: "/mnt/automated-linux/sources"

  tasks:
    - name: Install packages
      become: true
      ansible.builtin.package:
        name: "{{ packages }}"
        state: present

    - name: Create images
      changed_when: false
      ansible.builtin.command:
        cmd: "fallocate -l {{ item.size }} {{ item.image }}"
      with_items:
        - "{{ root_image }}"
        - "{{ sources_image }}"

    - name: Create filesystems
      changed_when: false
      ansible.builtin.command:
        cmd: "mkfs.ext4 {{ item.image }}"
      with_items:
        - "{{ root_image }}"
        - "{{ sources_image }}"

    - name: Mount images
      become: true
      ansible.posix.mount:
        path: "{{ item.mount_point }}"
        src: "{{ item.image }}"
        fstype: "ext4"
        state: "present"
      with_items:
        - "{{ root_image }}"
        - "{{ sources_image }}"
